DROP TABLE IF EXISTS wcf1_unfurl_url;
CREATE TABLE wcf1_unfurl_url (
	urlID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	url TEXT NOT NULL,
	urlHash VARCHAR(40) NOT NULL UNIQUE KEY,
	title VARCHAR(255) NOT NULL DEFAULT '',
	description TEXT, 
	imageUrl TEXT, 
	imageType ENUM('SQUARED', 'COVER', 'NOIMAGE') NOT NULL DEFAULT 'NOIMAGE',
	imageHash VARCHAR(44) NOT NULL DEFAULT '',
	status ENUM('PENDING', 'SUCCESSFUL', 'REJECTED') DEFAULT 'PENDING'
);